apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: salt-postgres
  namespace: murali
spec:
  serviceName: 'salt-postgres'
  replicas: 1
  selector:
    matchLabels:
      app: salt-postgres
  template:
    metadata:
      labels:
        app: salt-postgres
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:pg17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PORT
              value: '5432'
            - name: PGPORT
              value: '5432'
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          envFrom:
            - secretRef:
                name: salt-bot-secrets
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc
